### PR TITLE
Update mapfixes_surf.txt

### PR DESCRIPTION
**Pull request by Axs-Jid**

### CODE REVIEW

**Comment by dowoge** [comment]
I don't see this as a valid map "fix". Altering gameplay to make specific routes easier makes no sense.

**Comment by Axs-Jid** [comment]
it doesnt alter gameplay all i did was make the campfire noncollide (wr barely squeezes by it and the wall) sorry for putting an unclear description

**Comment by dowoge** [comment]
You only made this "map fix" because you couldn't hit the route easily, this has no reason to be accepted

**Comment by Axs-Jid** [comment]
this literally has precedent on ksf lol tho surf_mesa had triggers extending out of the ground and now they dont anymore because guess what it was annoying to do for the same result

**Comment by Axs-Jid** [comment]
https://prnt.sc/l9pe7VwyHlPd https://prnt.sc/3dZ7Cr9_pHuX

**Comment by Axs-Jid** [comment]
it is actually an inaccurate clip hitbox as you can see theres literally nothing there but theres a clip extending outwards https://prnt.sc/IuSQLCNXpoDR

**Comment by numberss** [comment]
can you change the fix to give it an accurate hitbox then instead of removing the hitbox entirely

**Comment by Axs-Jid** [comment]
if i have no other choice then yes but i still stand by my argument

**Comment by Axs-Jid** [comment]
can you run this by the map council and present my points i would like to see what they think

**Comment by numberss** [comment]
rejected by map council

**Pull request closed without merging**
